name: Linux
on:
  push:
    branches: [ main, zig-0.10.0 ]
  pull_request:
    branches: [ main, zig-0.10.0 ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: 0.10.0

    - run: zig build test
    - run: zig build test -Dstep-128
    - run: zig build
    - run: zig build -Dondemand
    - run: zig build -Dstep-128 
    - run: zig build -Dondemand -Dstep-128 